modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"

[[mods]]
modId="essential"
version="${file.jarVersion}"
displayName="Essential"
displayURL="https://essential.gg/"
description="Enhances your Minecraft with powerful features. Host worlds for free. Chat with friends. Create custom outfits. React with emotes. And many quality of life improvements!"

[[dependencies.essential]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
