modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"

[[mods]]
modId="essential"
version="${file.jarVersion}"
displayName="Essential"
displayURL="https://essential.gg/"
description="Provides essential features to Minecraft and our Partners."
